# Generated by Django 5.0.4 on 2025-11-25 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('complaint', 'Жалоба'), ('praise', 'Благодарность'), ('request', 'Запрос информации'), ('incident', 'Инцидент')], default='request', max_length=32)),
                ('priority', models.IntegerField(choices=[(1, 'Низкий'), (2, 'Средний'), (3, 'Высокий'), (4, 'Критический')], default=2)),
                ('status', models.CharField(choices=[('new', 'Новое'), ('acknowledged', 'Подтверждено'), ('in_progress', 'В работе'), ('resolved', 'Решено'), ('closed', 'Закрыто')], default='new', max_length=32)),
                ('assigned_group', models.CharField(blank=True, help_text='Ответственный департамент', max_length=128)),
                ('ack_deadline', models.DateTimeField(blank=True, null=True)),
                ('resolve_deadline', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=255)),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('email', 'Email'), ('vk', 'VKontakte'), ('other', 'Другое')], max_length=32)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('payload', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='tickets.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignee', models.CharField(max_length=255)),
                ('channel', models.CharField(default='internal', max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tickets.ticket')),
            ],
        ),
    ]
