# Generated by Django 5.0.4 on 2025-11-25 10:38

from django.db import migrations
from django.db.models import Count


def dedupe_channel_messages(apps, schema_editor):
    ChannelMessage = apps.get_model("tickets", "ChannelMessage")
    duplicates = (
        ChannelMessage.objects.values("external_id", "channel")
        .annotate(total=Count("id"))
        .filter(total__gt=1)
    )
    for dup in duplicates:
        qs = ChannelMessage.objects.filter(
            external_id=dup["external_id"], channel=dup["channel"]
        ).order_by("id")
        keep = qs.first()
        qs.exclude(id=keep.id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(dedupe_channel_messages, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="channelmessage",
            unique_together={("external_id", "channel")},
        ),
    ]
