# Generated by Django 5.0.4 on 2025-11-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticketresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmessage',
            name='is_transport',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='channelmessage',
            name='sentiment',
            field=models.CharField(choices=[('negative', 'Негатив'), ('neutral', 'Нейтрально'), ('positive', 'Позитив')], default='neutral', max_length=16),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_transport',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sentiment',
            field=models.CharField(choices=[('negative', 'Негатив'), ('neutral', 'Нейтрально'), ('positive', 'Позитив')], default='neutral', max_length=16),
        ),
    ]
