# Generated by Django 5.0.4 on 2025-11-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_channelmessage_is_transport_channelmessage_sentiment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmessage',
            name='transport_mode',
            field=models.CharField(choices=[('metro', 'Метро'), ('bus', 'Автобус'), ('tram', 'Трамвай'), ('train', 'Поезд'), ('airplane', 'Самолёт'), ('water', 'Водный транспорт'), ('taxi', 'Такси'), ('other', 'Другое')], default='other', max_length=16),
        ),
        migrations.AddField(
            model_name='ticket',
            name='transport_mode',
            field=models.CharField(choices=[('metro', 'Метро'), ('bus', 'Автобус'), ('tram', 'Трамвай'), ('train', 'Поезд'), ('airplane', 'Самолёт'), ('water', 'Водный транспорт'), ('taxi', 'Такси'), ('other', 'Другое')], default='other', max_length=16),
        ),
    ]
