# Generated by Django 5.0.4 on 2025-11-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_channelmessage_transport_mode_ticket_transport_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmessage',
            name='is_comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='channelmessage',
            name='parent_external_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='channelmessage',
            name='source_chat_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='channelmessage',
            name='thread_url',
            field=models.URLField(blank=True),
        ),
    ]
